version: 2
updates:
  # Maintain dependencies for Python backend
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "vanshika114"
    reviewers:
      - "vanshika114"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      python-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for Node.js frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    assignees:
      - "vanshika114"
    reviewers:
      - "vanshika114"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      npm-dependencies:
        patterns:
          - "*"

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "vanshika114"
    reviewers:
      - "vanshika114"
    labels:
      - "dependencies"
      - "actions"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    groups:
      actions-dependencies:
        patterns:
          - "*"
